### PR TITLE
Work in progress: Angular + ng-routing

### PR DESCRIPTION
**Pull request by AVGP**
:warning: **Do not merge yet** :warning: 

This is to foster communication and not ready yet

### CODE REVIEW

**Comment by SunboX** [comment]
Using Angular is ok for me. Heard good and bad things about it - like any other framework. ;) As far as we only use specific purpose frameworks (and no full featured like jQuery) I'm ok with it. ;)

**Comment by AVGP** [comment]
re: Templates
Well, there's no need to wrap it in an additional element really.
Angular already wraps it into the ng-view it will be loaded into, so I don't really see any reason to follow the <element> + <template> way (though I am happy to see that the W3C web components "template" element is used by Firefox OS)

re: Angular
It _is_ a full-featured framework, but it is modular and it is a great help in structuring the code. I have been working successfully with Angular in a bunch of mobile-centric projects and - unless used incorrectly - it has a good deal of benefits.

**Comment by SunboX** [comment]
Ok, I never used Angular (only Mootools (really a lot - 7 years), ExtJS, Sencha Touch and jQuery). Mostly (except ExtJS) my experience was ... it's nice to use, but at some point the framework is buggy or just can't do what you want - you will put more time into getting it work using framework xyz than it had taken building it from scratch.
But if you have good experience with Angular (I never used it! ;) ), so let's go with it. :) Maybe it's time for me to learn some Angular ... :D

**Comment by AVGP** [comment]
That reflects with my experience in using ExtJS, Knockout, Sencha Touch, Ember and some others...

The strength of Angular is that it enhances the DOM and works with plain javascript objects and dependency injection.

That already saves time and helps to lay out your application in a sensible way.
The biggest advantage: If you would ever decide "No, screw it, let's get rid of Angular" you can with not so much effort.
Soon you'll see what I mean :)

**Comment by SunboX** [comment]
Ok, sound's good. Let's use Angular. :)

**Pull request merged**
